
import java.awt.TextField;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class HomePage extends javax.swing.JFrame {
    
    public HomePage() {
        initComponents();
         ButtonGroup buttonGroup = new ButtonGroup();
         buttonGroup.add(jRadioButton1);
         buttonGroup.add(jRadioButton2);

    // to Select jRadioButton2 by default
    jRadioButton2.setSelected(true);
    jButton1.setVisible(false);
     JTextField[] textFields = new JTextField[]{jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9, jTextField10};
    
    jTextField11.getDocument().addDocumentListener(new DocumentListener() {
        public void changedUpdate(DocumentEvent e) {
            updateTextFields();
        }
        public void removeUpdate(DocumentEvent e) {
            updateTextFields();
        }
        public void insertUpdate(DocumentEvent e) {
            updateTextFields();
        }

        public void updateTextFields() {
            String input = jTextField11.getText().replaceAll("-", ""); // remove hyphens
            
            if(input.length() < 10 || input.length() > 13) {
                // Handle invalid input length
                return;
            }

            for (int i = 0; i < 10; i++) {
                char c = input.charAt(i);
                textFields[i].setText(String.valueOf(c));
            }
        }
        }
            );
    }
  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, -1));

        jRadioButton1.setText("ISBN Generator");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jRadioButton2.setText("Validity Checker");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jTextField11.setText("Type your ISBN code here");
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField11FocusGained(evt);
            }
        });
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 210, 40));

        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 50, 40));

        jTextField2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, 40));

        jTextField3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, 40));

        jTextField4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, 40));

        jTextField5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 50, 40));

        jTextField6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 50, 40));

        jTextField7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 50, 40));

        jTextField8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, 40));

        jTextField9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 50, 40));

        jTextField10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 50, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, -1));

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/137268-dancing-book.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
                if (jRadioButton1.isSelected()) 
                {
                    jButton1.setVisible(true);
                    jButton2.setVisible(false);
                 }        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       if (jRadioButton2.isSelected()) 
                {
                    jButton2.setVisible(true);
                    jButton1.setVisible(false);
                 }    
    }//GEN-LAST:event_jRadioButton2ActionPerformed
public void clearAllTextFields() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    jTextField10.setText("");
}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          // Get the values from the text fields
    int[] digits = new int[10];
    try {
        digits[0] = Integer.parseInt(jTextField1.getText());
        digits[1] = Integer.parseInt(jTextField2.getText());
        digits[2] = Integer.parseInt(jTextField3.getText());
        digits[3] = Integer.parseInt(jTextField4.getText());
        digits[4] = Integer.parseInt(jTextField5.getText());
        digits[5] = Integer.parseInt(jTextField6.getText());
        digits[6] = Integer.parseInt(jTextField7.getText());
        digits[7] = Integer.parseInt(jTextField8.getText());
        digits[8] = Integer.parseInt(jTextField9.getText());
        digits[9] = Integer.parseInt(jTextField10.getText());
    } catch (NumberFormatException e) {
        // Invalid input, display an error message
        JOptionPane.showMessageDialog(this, "Invalid input. Please enter only digits 0-9 or X for the last digit.", "Error", JOptionPane.ERROR_MESSAGE);
        clearAllTextFields();
        return;
    }

    // Check if the digits are in the range 0-9
    for (int i = 0; i < 9; i++) {
        if (digits[i] < 0 || digits[i] > 9) {
            // Invalid input, display an error message
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter only digits 0-9 for the first 9 digits, where the first digit is 1 or 0", "Error", JOptionPane.ERROR_MESSAGE);
            clearAllTextFields();
            return;
            
        }
    }

    if (digits[9] < 0 || digits[9] > 10 || (digits[9] == 10 && jTextField10.getText().charAt(0) != 'X')) {
        // Invalid input, display an error message
        JOptionPane.showMessageDialog(this, "Invalid input. The last digit should be 0-9 or X.", "Error", JOptionPane.ERROR_MESSAGE);
        clearAllTextFields();
        return;
    }

    // Validate the ISBN number
    int sum = 0;
    for (int i = 0; i < 9; i++) {
        sum += digits[i] * (10 - i);
    }

    int checkDigit = 0;
    if(jTextField10.getText().charAt(0) == 'X') {
        checkDigit = 10;
    } else {
        checkDigit = digits[9];
    }

    if ((sum + checkDigit) % 11 == 0) {
        JOptionPane.showMessageDialog(this, "Valid ISBN number.", "Success", JOptionPane.INFORMATION_MESSAGE);
        clearAllTextFields();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid ISBN number.", "Error", JOptionPane.ERROR_MESSAGE);
        clearAllTextFields();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
           if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jButton2ActionPerformed(null);
    }   

    }//GEN-LAST:event_jButton2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        move(evt, jTextField1, jTextField2, jTextField1);
    }//GEN-LAST:event_jTextField1KeyPressed

    private void move(KeyEvent evt, JTextField currentField, JTextField rightField, JTextField leftField){
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            // Move focus to the previous text field
            if (currentField.getCaretPosition() == 0) {
                leftField.requestFocus();
                leftField.setCaretPosition(leftField.getText().length());
            } else {
                currentField.setCaretPosition(currentField.getCaretPosition() - 1);
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            // Move focus to the next text field
            if (currentField.getCaretPosition() == currentField.getText().length()) {
                rightField.requestFocus();
                rightField.setCaretPosition(0);
            } else {
                currentField.setCaretPosition(currentField.getCaretPosition() + 1);
            }
        }
    }
    
    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    JTextField[] textFields = new JTextField[]{jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9, jTextField10};
    char[] isbnCharacters = new char[10];
    boolean foundXYZ = false;
    
    for(int i=0; i<10; i++){
        String text = textFields[i].getText().toUpperCase();
        isbnCharacters[i] = text.charAt(0);
        if(text.equals("X") || text.equals("Y") || text.equals("Z")) {
            foundXYZ = true;
        }
    }
    
    if(foundXYZ) {
        List<String> generatedISBNs = new ArrayList<>();
        generateISBNs(isbnCharacters, 0, generatedISBNs);
        // Display the generated ISBNs
        if(generatedISBNs.size() > 1) {
            JOptionPane.showMessageDialog(this, "Multiple valid ISBNs generated:\n" + String.join("\n", generatedISBNs));
        } else if(generatedISBNs.size() == 1) {
            JOptionPane.showMessageDialog(this, "Valid ISBN generated:\n" + generatedISBNs.get(0));
            clearAllTextFields();
        } else {
            JOptionPane.showMessageDialog(this, "No valid ISBN could be generated.");
        }
    } else {
        // Display error when no X, Y, Z are found in the sequence
        JOptionPane.showMessageDialog(this, "Error: Enter X, Y, or Z");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusGained
         jTextField11.setText("");
    }//GEN-LAST:event_jTextField11FocusGained

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        move(evt, jTextField2, jTextField3, jTextField1);
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        move(evt, jTextField3, jTextField4, jTextField2);   
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        move(evt, jTextField4, jTextField5, jTextField3);
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        move(evt, jTextField5, jTextField6, jTextField4);
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        move(evt, jTextField6, jTextField7, jTextField5);
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        move(evt, jTextField7, jTextField8, jTextField6);
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        move(evt, jTextField8, jTextField9, jTextField7);
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        move(evt, jTextField9, jTextField10, jTextField8);
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
         move(evt, jTextField10, jTextField1, jTextField9);
    }//GEN-LAST:event_jTextField10KeyPressed

// This method generates all possible ISBNs by replacing X, Y, Z with valid digits
private void generateISBNs(char[] isbnCharacters, int index, List<String> generatedISBNs) {
    if(index == isbnCharacters.length) {
        if(checkValidISBN(isbnCharacters)) {
            generatedISBNs.add(new String(isbnCharacters));
        }
        return;
    }
    if(isbnCharacters[index] == 'X' || isbnCharacters[index] == 'Y' || isbnCharacters[index] == 'Z') {
        for(int j=0; j<=9; j++) {
            isbnCharacters[index] = (char)('0' + j);
            generateISBNs(isbnCharacters, index + 1, generatedISBNs);
        }
        if(index == 9) { // The last character can be 'X'
            isbnCharacters[index] = 'X';
            generateISBNs(isbnCharacters, index + 1, generatedISBNs);
        }
        isbnCharacters[index] = 'X'; // Reset the character back to 'X'
    } else {
        generateISBNs(isbnCharacters, index + 1, generatedISBNs);
    }
}
// This method checks whether the given 10-digit sequence is a valid ISBN
private boolean checkValidISBN(char[] isbnCharacters) {
    int sum = 0;
    for(int i=0; i<10; i++) {
        int digit = (isbnCharacters[i] == 'X') ? 10 : (isbnCharacters[i] - '0');
        sum += digit * (i+1);
    }
    return sum % 11 == 0;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
